contact: ARC.Education@ucl.ac.uk

title: "In2Research Journeys"
includeleftnav: True
#short: ARC Edu # shown as crumbs

baseurl: /in2research_journeys
#url: http://localhost:4000

remote_theme: UCL-ARC/indigo-jekyll

crumbs:
  - link: https://www.ucl.ac.uk/arc
    text: Advanced Research Computing
  - link: https://www.ucl.ac.uk/advanced-research-computing/education
    text: Education
  - link: /in2research_journeys/
    text: in2research journeys

plugins:
  - jekyll-remote-theme
  - jekyll-feed

include: # NOTE: This is not a path, but the directories name, wherever they are
  - _static
  - _modules

exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock

collections:
  authors:
    output: true

# defaults:
#   - scope: {path: ""}
#     values: {layout: default}

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  hard_wrap: false
  input: GFM

